
# coordinator messages
VOTE_REQUEST = 'VOTE_REQUEST'
PREPARE_COMMIT = 'PREPARE_COMMIT'
GLOBAL_COMMIT = 'GLOBAL_COMMIT'
GLOBAL_ABORT = 'GLOBAL_ABORT'

# participant messages
READY_COMMIT = 'READY_COMMIT'
VOTE_COMMIT = 'VOTE_COMMIT'
VOTE_ABORT = 'VOTE_ABORT'
NEED_DECISION = 'NEED_DECISION'

# participant decisions
LOCAL_ABORT = 'LOCAL_ABORT'
LOCAL_SUCCESS = 'LOCAL_SUCCESS'

# find new coordinator
NEW_COORDINATOR = 'NEW_COORDINATOR'
CONFIRM_COORD = 'CONFIRM_COORD'

# fail-noisy crash timeout
TIMEOUT = 1
